# Generated by Django 5.0.2 on 2025-07-06 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_description_productvariant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
