# Generated by Django 5.0.2 on 2025-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_merge_20250710_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.JSONField(blank=True, help_text='List of formatted address strings', null=True, verbose_name='All Addresses'),
        ),
    ]
