# Generated by Django 5.0.2 on 2025-07-09 17:55

import companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_company_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='registration number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.CharField(max_length=100, unique=True, verbose_name='Shopify Customer ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[companies.models.validate_phone_number], verbose_name='Phone')),
                ('number_of_orders', models.IntegerField(default=0, validators=[companies.models.validate_order_amount], verbose_name='Number of Orders')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[companies.models.validate_amount], verbose_name='Total Amount Spent')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, validators=[companies.models.validate_currency_code], verbose_name='Currency Code')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('verified_email', models.BooleanField(default=False, verbose_name='Verified Email')),
                ('valid_email_address', models.BooleanField(default=False, verbose_name='Valid Email Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('tags', models.TextField(blank=True, null=True, validators=[companies.models.validate_tags], verbose_name='Tags')),
                ('lifetime_duration', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[companies.models.validate_amount], verbose_name='Lifetime Duration')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete')),
                ('default_address_formatted_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Address Area')),
                ('default_address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Address Line')),
                ('addresses', models.JSONField(blank=True, null=True, verbose_name='All Addresses')),
                ('src', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Src')),
                ('cust_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
