# Generated by Django 5.0.2 on 2025-07-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_company_fields'),
        ('companies', '0009_alter_company_options_company_email_and_more'),
    ]

    operations = [
    ]
