# Generated by Django 5.0.2 on 2025-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, help_text='Unique Shopify Product ID or internal ID', max_length=100, null=True, unique=True),
        ),
    ]
