# Generated by Django 5.0.2 on 2025-07-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='type',
            field=models.CharField(blank=True, help_text='Type of variant (e.g. Size, Color)', max_length=100, null=True),
        ),
    ]
